# Get A list's Tasks
GET http://localhost:3000/lists/6113be4a694a365e1db2063f/tasks

# Create a Task

POST http://localhost:3000/lists/6113be4a694a365e1db2063f/tasks/new
content-type: application/json

{
    "task": "non async test"
}

# Delete a Task
DELETE http://localhost:3000/lists/6113be4a694a365e1db2063f/tasks/61150e97879a7211529bc933


# list index
GET http://localhost:3000/lists/

# Create a list
POST http://localhost:3000/lists/
content-type: application/json

{
    "name": "Project 2"
}

