@listId = 6113be4a694a365e1db2063f
@taskId = 6113c5cbe543f57d67059c8f
@userId = ""


# Get A list's Tasks
GET http://localhost:3000/lists/{{listId}}/tasks


# Create a Task
POST http://localhost:3000/lists/{{listId}}/tasks/new
content-type: application/json

{
    "task": "non async test"
}


# Delete a Task
DELETE http://localhost:3000/lists/{{listId}}/tasks/{{taskId}}


# Toggle Task
POST http://localhost:3000/lists/{{listId}}/tasks/{{taskId}}/toggle



# LIST REQUESTS
# LIST REQUESTS
# LIST REQUESTS

# list index
GET http://localhost:3000/lists/

# Create a list
POST http://localhost:3000/lists/
content-type: application/json

{
    "name": "Project 2"
}

