# index
GET http://localhost:3000/users

# Create
POST http://localhost:3000/users
content-type: application/json

{
    "name": "Sam"
}

# Update
PATCH http://localhost:3000/users/61168bff7865c1053870d708
content-type: application/json

{
    "name": "Samuel"
}

# Delete

# 